### ISSUE TITLE
zafira-client: we have to add explicit jersey-common dependency to the client

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/zafira#1194]
some client projects can't register test run correctly. it seems like we have to register explicitly 2.27 jersey-common dependency inside zafira-client. it would be nice to have snapshot client build for testing

01:22:26 java.lang.ExceptionInInitializerError
01:22:26 	at com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$Wadl.<init>(JSONRootElementProvider.java:138)
01:22:26 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
01:22:26 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
01:22:26 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
01:22:26 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01:22:26 	at com.sun.jersey.core.spi.component.ComponentConstructor._getInstance(ComponentConstructor.java:210)
01:22:26 	at com.sun.jersey.core.spi.component.ComponentConstructor.getInstance(ComponentConstructor.java:180)
01:22:26 	at com.sun.jersey.core.spi.component.ProviderFactory.__getComponentProvider(ProviderFactory.java:166)
01:22:26 	at com.sun.jersey.core.spi.component.ProviderFactory.getComponentProvider(ProviderFactory.java:137)
01:22:26 	at com.sun.jersey.core.spi.component.ProviderServices.getComponent(ProviderServices.java:283)
01:22:26 	at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:163)
01:22:26 	at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176)
01:22:26 	at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162)
01:22:26 	at com.sun.jersey.api.client.Client.init(Client.java:343)
01:22:26 	at com.sun.jersey.api.client.Client.access$000(Client.java:119)
01:22:26 	at com.sun.jersey.api.client.Client$1.f(Client.java:192)
01:22:26 	at com.sun.jersey.api.client.Client$1.f(Client.java:188)
01:22:26 	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
01:22:26 	at com.sun.jersey.api.client.Client.<init>(Client.java:188)
01:22:26 	at com.sun.jersey.api.client.Client.<init>(Client.java:160)
01:22:26 	at com.sun.jersey.api.client.Client.create(Client.java:673)
01:22:26 	at com.qaprosoft.zafira.client.ZafiraClient.<init>(ZafiraClient.java:85)
01:22:26 	at com.qaprosoft.zafira.listener.ZafiraListener.initializeZafira(ZafiraListener.java:605)
01:22:26 	at com.qaprosoft.zafira.listener.ZafiraListener.onStart(ZafiraListener.java:123)
01:22:26 	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:199)
01:22:26 	at org.testng.SuiteRunner.run(SuiteRunner.java:252)
01:22:26 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:22:26 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
01:22:26 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
01:22:26 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
01:22:26 	at org.testng.TestNG.run(TestNG.java:1057)
01:22:26 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
01:22:26 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
01:22:26 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
01:22:26 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
01:22:26 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
01:22:26 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
01:22:26 Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
01:22:26 	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
01:22:26 	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
01:22:26 	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:179)
01:22:26 	at com.sun.jersey.core.header.MediaTypes.<clinit>(MediaTypes.java:65)
01:22:26 	... 37 more
01:22:26 Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
01:22:26 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
01:22:26 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
01:22:26 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
01:22:26 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
01:22:26 	at java.lang.Class.forName0(Native Method)
01:22:26 	at java.lang.Class.forName(Class.java:264)
01:22:26 	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:115)
01:22:26 	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:225)
01:22:26 	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
01:22:26 	... 40 more

**Comment by vdelendik** [comment]
issue on a project client side. not a zafira defect
