### ISSUE TITLE
Zafira is not working with testng.

### ISSUE THREAD

**Issue by rajeshchy** [qaprosoft/zafira#1329]
[main] INFO com.qaprosoft.zafira.listener.ZafiraListener - Zafira is available
[main] ERROR com.qaprosoft.zafira.client.ZafiraClient - Unable to authorize user
javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
	at com.owlike.genson.ext.jaxrs.GensonJsonConverter.readFrom(GensonJsonConverter.java:127)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at com.qaprosoft.zafira.client.ZafiraClient.getUserProfile(ZafiraClient.java:147)
	at com.qaprosoft.zafira.listener.ZafiraListener.onStart(ZafiraListener.java:138)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:301)
	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to type class com.qaprosoft.zafira.models.dto.user.UserType
	at com.owlike.genson.Genson.deserialize(Genson.java:442)
	at com.owlike.genson.ext.jaxrs.GensonJsonConverter.readFrom(GensonJsonConverter.java:125)
	... 14 more
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to property 'permissions' of class class com.qaprosoft.zafira.models.dto.user.UserType
	at com.owlike.genson.reflect.PropertyMutator.couldNotDeserialize(PropertyMutator.java:49)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:32)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:110)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:93)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:57)
	at com.owlike.genson.Genson.deserialize(Genson.java:440)
	... 15 more
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to property 'name' of class class com.qaprosoft.zafira.models.db.Permission
	at com.owlike.genson.reflect.PropertyMutator.couldNotDeserialize(PropertyMutator.java:49)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:32)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:110)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:93)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:57)
	at com.owlike.genson.convert.DefaultConverters$CollectionConverter.deserialize(DefaultConverters.java:106)
	at com.owlike.genson.convert.DefaultConverters$CollectionConverter.deserialize(DefaultConverters.java:89)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:57)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:30)
	... 19 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.qaprosoft.zafira.models.db.Permission.Name.MODIFY_LAUNCHERS
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.owlike.genson.convert.DefaultConverters$EnumConverter.deserialize(DefaultConverters.java:872)
	at com.owlike.genson.convert.DefaultConverters$EnumConverter.deserialize(DefaultConverters.java:858)
	at com.owlike.genson.convert.NullConverter$NullConverterWrapper.deserialize(NullConverter.java:57)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:30)
	... 26 more
[main] ERROR com.qaprosoft.zafira.listener.ZafiraListener - Undefined error during test run registration!
java.lang.NullPointerException
	at com.qaprosoft.zafira.listener.ZafiraListener.onStart(ZafiraListener.java:207)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:301)
	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by rajeshchy** [comment]
When I hit the get user profile api using postman then I am able to get the response. 

URL: http://localhost:8080/zafira-ws/api/users/profile

{
    "id": 2,
    "username": "qpsdemo",
    "firstName": "Rajesh",
    "lastName": "Chaudhary",
    "password": "EQsXqYwMHQtx0d+AzIbxU8scOLZbMKCq",
    "roles": [
        "ROLE_ADMIN"
    ],
    "permissions": [
        {
            "id": 1,
            "modifiedAt": null,
            "createdAt": null,
            "name": "VIEW_HIDDEN_DASHBOARDS",
            "block": null
        },
        {
            "id": 2,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_DASHBOARDS",
            "block": null
        },
        {
            "id": 3,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_WIDGETS",
            "block": null
        },
        {
            "id": 4,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_TEST_RUN_VIEWS",
            "block": null
        },
        {
            "id": 5,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_TEST_RUNS",
            "block": null
        },
        {
            "id": 6,
            "modifiedAt": null,
            "createdAt": null,
            "name": "TEST_RUNS_CI",
            "block": null
        },
        {
            "id": 7,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_TESTS",
            "block": null
        },
        {
            "id": 8,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_USERS",
            "block": null
        },
        {
            "id": 9,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_USER_GROUPS",
            "block": null
        },
        {
            "id": 10,
            "modifiedAt": null,
            "createdAt": null,
            "name": "VIEW_USERS",
            "block": null
        },
        {
            "id": 11,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_SETTINGS",
            "block": null
        },
        {
            "id": 12,
            "modifiedAt": null,
            "createdAt": null,
            "name": "VIEW_SETTINGS",
            "block": null
        },
        {
            "id": 13,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_MONITORS",
            "block": null
        },
        {
            "id": 14,
            "modifiedAt": null,
            "createdAt": null,
            "name": "VIEW_MONITORS",
            "block": null
        },
        {
            "id": 15,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_PROJECTS",
            "block": null
        },
        {
            "id": 16,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_INTEGRATIONS",
            "block": null
        },
        {
            "id": 17,
            "modifiedAt": null,
            "createdAt": null,
            "name": "VIEW_INTEGRATIONS",
            "block": null
        },
        {
            "id": 18,
            "modifiedAt": null,
            "createdAt": null,
            "name": "INVITE_USERS",
            "block": null
        },
        {
            "id": 19,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_INVITATIONS",
            "block": null
        },
        {
            "id": 20,
            "modifiedAt": null,
            "createdAt": null,
            "name": "MODIFY_LAUNCHERS",
            "block": null
        },
        {
            "id": 21,
            "modifiedAt": null,
            "createdAt": null,
            "name": "VIEW_LAUNCHERS",
            "block": null
        }
    ],
    "preferences": [
        {
            "id": 4,
            "modifiedAt": 1550045652184,
            "createdAt": 1550045652184,
            "name": "REFRESH_INTERVAL",
            "value": "0"
        },
        {
            "id": 5,
            "modifiedAt": 1550045652184,
            "createdAt": 1550045652184,
            "name": "DEFAULT_DASHBOARD",
            "value": "General"
        },
        {
            "id": 6,
            "modifiedAt": 1550045652184,
            "createdAt": 1550045652184,
            "name": "THEME",
            "value": "32"
        }
    ],
    "lastLogin": 1550284949326,
    "source": "INTERNAL",
    "status": "ACTIVE"
}

**Comment by vdelendik** [comment]
@rajeshchy, please clone and test using released 3.3.37 tag: https://github.com/qaprosoft/zafira/releases/tag/3.3.37

currently master combined several major features and we have mismatch with default DB layer.
Also take a look to https://github.com/qaprosoft/qps-infra where also released 3.3.37 Zafira is embedded
