### ISSUE TITLE
Test run results aren't sent to testrail

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/zafira#1669]
HttpMethod: GET
URL: https://***.zebrunner.com/zafira-ws/api/tags/b4f8c340-2b58-446e-9033-55a6cafb61ef/integration?integrationTag=TESTRAIL_TESTCASE_UUID
Content-type: application/json
Authorization: *****
Sending request to url: https://***.zebrunner.com/zafira-ws/api/tags/ed8129c9-66b5-4215-8d91-78a0ad6dfd52/integration?integrationTag=TESTRAIL_TESTCASE_UUID
Response Code: HTTP/1.1 500 Internal Server Error
[Pipeline] echo
java.lang.IllegalStateException: hudson.AbortException: Fail: the returned code 500 is not in the accepted range: [[200‥200]]
	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:198)
	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:67)
	at hudson.remoting.UserRequest.perform(UserRequest.java:208)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:360)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hursevich** [comment]
Fixed
